---
image: cincproject/omnibus-debian

stages:
  - patch
  - package
  - test
  - cleanup
  - deploy
  - publish

variables:
  ORIGIN: https://github.com/chef/chef-foundation.git
  REF: main
  CHANNEL: unstable
  CINC_PRODUCT: cinc-foundation
  OMNIBUS_FIPS_MODE: "true"
  GIT_CACHE: "true"
  OMNIBUS_LOG_LEVEL: "info"

workflow:
  rules:
    # Run if we trigger a pipeline from the web
    - if: $CI_PIPELINE_SOURCE == "web"
    # Run if we trigger a pipeline from another project (i.e. upstream/chef-foundation)
    - if: $CI_PIPELINE_SOURCE == "pipeline"
    # Run if this is a merge request
    - if: $CI_MERGE_REQUEST_ID

include:
  - local: .gitlab/package.yml
  - local: .gitlab/test.yml

patch:
  stage: patch
  tags:
    - docker-x86_64
  script:
    - ./patch.sh
  artifacts:
    expire_in: 1mo
    paths:
      - chef-foundation/

# Package stage

package:source:
  stage: package
  needs:
    - patch
  tags:
    - docker-x86_64
  script:
    - ./build-source.sh
  artifacts:
    expire_in: 1mo
    paths:
      - source/*

package:amazonlinux-2:x86_64:
  extends: .package:amazonlinux
  image: cincproject/omnibus-amazonlinux:2
  cache:
    key: amazonlinux:2:x86_64
  tags:
    - docker-x86_64
  variables:
    PLATFORM_VER: "2"

package:amazonlinux-2:aarch64:
  extends: .package:amazonlinux
  image: cincproject/omnibus-amazonlinux:2
  cache:
    key: amazonlinux:2:aarch64
  tags:
    - docker-aarch64
  variables:
    PLATFORM_VER: "2"
    OMNIBUS_FIPS_MODE: "false"

package:centos-7:x86_64:
  extends: .package:centos
  image: cincproject/omnibus-centos:7
  cache:
    key: centos:7:x86_64
  tags:
    - docker-x86_64
  variables:
    PLATFORM_VER: "7"

package:centos-7:aarch64:
  extends: .package:centos
  image: cincproject/omnibus-centos:7
  cache:
    key: centos:7:aarch64
  tags:
    - docker-aarch64
  variables:
    PLATFORM_VER: "7"
    OMNIBUS_FIPS_MODE: "false"

package:centos-7:ppc64le:
  extends: .package:centos
  image: cincproject/omnibus-centos:7
  cache:
    key: centos:7:ppc64le
  tags:
    - docker-ppc64le
  variables:
    PLATFORM_VER: "7"

package:centos-8:x86_64:
  extends: .package:centos
  image: cincproject/omnibus-centos-stream:8
  cache:
    key: centos-stream:8:x86_64
  tags:
    - docker-x86_64
  variables:
    PLATFORM_VER: "8"

package:centos-8:aarch64:
  extends: .package:centos
  image: cincproject/omnibus-centos-stream:8
  cache:
    key: centos-stream:8:aarch64
  tags:
    - docker-aarch64
  variables:
    PLATFORM_VER: "8"
    OMNIBUS_FIPS_MODE: "false"

package:centos-8:ppc64le:
  extends: .package:centos
  image: cincproject/omnibus-centos-stream:8
  cache:
    key: centos-stream:8:ppc64le
  tags:
    - docker-ppc64le
  variables:
    PLATFORM_VER: "8"

package:centos-9:x86_64:
  extends: .package:centos
  image: cincproject/omnibus-centos-stream:9
  cache:
    key: centos-stream:9:x86_64
  tags:
    - docker-x86_64
  variables:
    PLATFORM_VER: "9"

package:centos-9:aarch64:
  extends: .package:centos
  image: cincproject/omnibus-centos-stream:9
  cache:
    key: centos-stream:9:aarch64
  tags:
    - docker-aarch64
  variables:
    PLATFORM_VER: "9"
    OMNIBUS_FIPS_MODE: "false"

package:centos-9:ppc64le:
  extends: .package:centos
  image: cincproject/omnibus-centos-stream:9
  cache:
    key: centos-stream:9:ppc64le
  tags:
    - docker-ppc64le-p9
  variables:
    PLATFORM_VER: "9"

package:debian-9:x86_64:
  extends: .package:debian
  image: cincproject/omnibus-debian:9
  cache:
    key: debian:9:x86_64
  tags:
    - docker-x86_64
  variables:
    PLATFORM_VER: "9"

package:debian-10:x86_64:
  extends: .package:debian
  image: cincproject/omnibus-debian:10
  cache:
    key: debian:10:x86_64
  tags:
    - docker-x86_64
  variables:
    PLATFORM_VER: "10"

package:debian-10:aarch64:
  extends: .package:debian
  image: cincproject/omnibus-debian:10
  cache:
    key: debian:10:aarch64
  tags:
    - docker-aarch64
  variables:
    PLATFORM_VER: "10"
    OMNIBUS_FIPS_MODE: "false"

package:debian-11:x86_64:
  extends: .package:debian
  image: cincproject/omnibus-debian:11
  cache:
    key: debian:11:x86_64
  tags:
    - docker-x86_64
  variables:
    PLATFORM_VER: "11"

package:debian-11:aarch64:
  extends: .package:debian
  image: cincproject/omnibus-debian:11
  cache:
    key: debian:11:aarch64
  tags:
    - docker-aarch64
  variables:
    PLATFORM_VER: "11"
    OMNIBUS_FIPS_MODE: "false"

package:debian-12:x86_64:
  extends: .package:debian
  image: cincproject/omnibus-debian:12
  cache:
    key: debian:12:x86_64
  tags:
    - docker-x86_64
  variables:
    PLATFORM_VER: "12"

package:debian-12:aarch64:
  extends: .package:debian
  image: cincproject/omnibus-debian:12
  cache:
    key: debian:12:aarch64
  tags:
    - docker-aarch64
  variables:
    PLATFORM_VER: "12"
    OMNIBUS_FIPS_MODE: "false"

package:macos-10.15:
  extends: .package:macos
  cache:
    key: macos:10.15
  tags:
    - macos-10.15
  variables:
    PLATFORM_VER: "10.15"
    OMNIBUS_FIPS_MODE: "false"

package:macos-11:
  extends: .package:macos
  cache:
    key: macos:11
  tags:
    - macos-11
  variables:
    PLATFORM_VER: "11"
    OMNIBUS_FIPS_MODE: "false"

package:macos-11:aarch64:
  extends: .package:macos
  cache:
    key: macos:11:aarch64
  tags:
    - macos-11-aarch64
  variables:
    PLATFORM_VER: "11"
    OMNIBUS_FIPS_MODE: "false"

package:macos-12:
  extends: .package:macos
  cache:
    key: macos:12
  tags:
    - macos-12
  variables:
    PLATFORM_VER: "12"
    OMNIBUS_FIPS_MODE: "false"

package:opensuse-15:x86_64:
  extends: .package:opensuse
  image: cincproject/omnibus-opensuse:15.2
  cache:
    key: opensuse:15:x86_64
  tags:
    - docker-x86_64
  variables:
    PLATFORM_VER: "15"

package:opensuse-15:aarch64:
  extends: .package:opensuse
  image: cincproject/omnibus-opensuse:15.2
  cache:
    key: opensuse:15:aarch64
  tags:
    - docker-aarch64
  variables:
    PLATFORM_VER: "15"
    OMNIBUS_FIPS_MODE: "false"

package:windows-2012r2:
  extends: .package:windows
  cache:
    key: windows-2012r2
  tags:
    - windows-x64-ucrt64
  variables:
    PLATFORM_VER: "2012r2"

package:ubuntu-18.04:x86_64:
  extends: .package:ubuntu
  image: cincproject/omnibus-ubuntu:18.04
  cache:
    key: ubuntu:18.04:x86_64
  tags:
    - docker-x86_64
  variables:
    PLATFORM_VER: "18.04"

package:ubuntu-18.04:aarch64:
  extends: .package:ubuntu
  image: cincproject/omnibus-ubuntu:18.04
  cache:
    key: ubuntu:18.04:aarch64
  tags:
    - docker-aarch64
  variables:
    PLATFORM_VER: "18.04"
    OMNIBUS_FIPS_MODE: "false"

package:rhel-7:s390x:
  extends: .package:centos
  image: cincproject/omnibus-rhel:7
  cache:
    key: rhel:7:s390x
  tags:
    - docker-s390x
  needs:
    - patch
  variables:
    PLATFORM_VER: "7"

package:rhel-8:s390x:
  extends: .package:centos
  image: cincproject/omnibus-rhel:8
  cache:
    key: rhel:8:s390x
  tags:
    - docker-s390x
  needs:
    - patch
  variables:
    PLATFORM_VER: "8"

package:ubuntu-20.04:x86_64:
  extends: .package:ubuntu
  image: cincproject/omnibus-ubuntu:20.04
  cache:
    key: ubuntu:20.04:x86_64
  tags:
    - docker-x86_64
  variables:
    PLATFORM_VER: "20.04"

package:ubuntu-20.04:aarch64:
  extends: .package:ubuntu
  image: cincproject/omnibus-ubuntu:20.04
  cache:
    key: ubuntu:20.04:aarch64
  tags:
    - docker-aarch64
  variables:
    PLATFORM_VER: "20.04"
    OMNIBUS_FIPS_MODE: "false"

package:ubuntu-22.04:x86_64:
  extends: .package:ubuntu
  image: cincproject/omnibus-ubuntu:22.04
  cache:
    key: ubuntu:22.04:x86_64
  tags:
    - docker-x86_64
  variables:
    PLATFORM_VER: "22.04"

package:ubuntu-22.04:aarch64:
  extends: .package:ubuntu
  image: cincproject/omnibus-ubuntu:22.04
  cache:
    key: ubuntu:22.04:aarch64
  tags:
    - docker-aarch64
  variables:
    PLATFORM_VER: "22.04"
    OMNIBUS_FIPS_MODE: "false"

test:amazonlinux-2:x86_64:
  extends: .test:amazonlinux
  image: cincproject/omnibus-amazonlinux:2
  needs:
    - package:amazonlinux-2:x86_64
  tags:
    - docker-x86_64
  variables:
    PLATFORM_VER: "2"

test:amazonlinux-2:aarch64:
  extends: .test:amazonlinux
  image: cincproject/omnibus-amazonlinux:2
  needs:
    - package:amazonlinux-2:aarch64
  tags:
    - docker-aarch64
  variables:
    PLATFORM_VER: "2"

test:centos-7:x86_64:
  extends: .test:centos
  image: cincproject/omnibus-centos:7
  needs:
    - package:centos-7:x86_64
  tags:
    - docker-x86_64
  variables:
    PLATFORM_VER: "7"

test:centos-7:aarch64:
  extends: .test:centos
  image: cincproject/omnibus-centos:7
  needs:
    - package:centos-7:aarch64
  tags:
    - docker-aarch64
  variables:
    PLATFORM_VER: "7"

test:centos-7:ppc64le:
  extends: .test:centos
  image: cincproject/omnibus-centos:7
  needs:
    - package:centos-7:ppc64le
  tags:
    - docker-ppc64le
  variables:
    PLATFORM_VER: "7"

test:centos-8:x86_64:
  extends: .test:centos
  image: cincproject/omnibus-centos-stream:8
  needs:
    - package:centos-8:x86_64
  tags:
    - docker-x86_64
  variables:
    PLATFORM_VER: "8"

test:centos-8:aarch64:
  extends: .test:centos
  image: cincproject/omnibus-centos-stream:8
  needs:
    - package:centos-8:aarch64
  tags:
    - docker-aarch64
  variables:
    PLATFORM_VER: "8"

test:centos-8:ppc64le:
  extends: .test:centos
  image: cincproject/omnibus-centos-stream:8
  needs:
    - package:centos-8:ppc64le
  tags:
    - docker-ppc64le
  variables:
    PLATFORM_VER: "8"

test:centos-9:x86_64:
  extends: .test:centos
  image: cincproject/omnibus-centos-stream:9
  needs:
    - package:centos-9:x86_64
  tags:
    - docker-x86_64
  variables:
    PLATFORM_VER: "9"

test:centos-9:aarch64:
  extends: .test:centos
  image: cincproject/omnibus-centos-stream:9
  needs:
    - package:centos-9:aarch64
  tags:
    - docker-aarch64
  variables:
    PLATFORM_VER: "9"

test:centos-9:ppc64le:
  extends: .test:centos
  image: cincproject/omnibus-centos-stream:9
  needs:
    - package:centos-9:ppc64le
  tags:
    - docker-ppc64le-p9
  variables:
    PLATFORM_VER: "9"

test:debian-9:x86_64:
  extends: .test:debian
  image: cincproject/omnibus-debian:9
  needs:
    - package:debian-9:x86_64
  tags:
    - docker-x86_64
  variables:
    PLATFORM_VER: "9"

test:debian-10:x86_64:
  extends: .test:debian
  image: cincproject/omnibus-debian:10
  needs:
    - package:debian-10:x86_64
  tags:
    - docker-x86_64
  variables:
    PLATFORM_VER: "10"

test:debian-10:aarch64:
  extends: .test:debian
  image: cincproject/omnibus-debian:10
  needs:
    - package:debian-10:aarch64
  tags:
    - docker-aarch64
  variables:
    PLATFORM_VER: "10"

test:debian-11:x86_64:
  extends: .test:debian
  image: cincproject/omnibus-debian:11
  needs:
    - package:debian-11:x86_64
  tags:
    - docker-x86_64
  variables:
    PLATFORM_VER: "11"

test:debian-11:aarch64:
  extends: .test:debian
  image: cincproject/omnibus-debian:11
  needs:
    - package:debian-11:aarch64
  tags:
    - docker-aarch64
  variables:
    PLATFORM_VER: "11"

test:debian-12:x86_64:
  extends: .test:debian
  image: cincproject/omnibus-debian:12
  needs:
    - package:debian-12:x86_64
  tags:
    - docker-x86_64
  variables:
    PLATFORM_VER: "12"

test:debian-12:aarch64:
  extends: .test:debian
  image: cincproject/omnibus-debian:12
  needs:
    - package:debian-12:aarch64
  tags:
    - docker-aarch64
  variables:
    PLATFORM_VER: "12"

test:macos-10.15:
  extends: .test:macos
  needs:
    - package:macos-10.15
  tags:
    - macos-10.15
  variables:
    PLATFORM_VER: "10.15"

test:macos-11:
  extends: .test:macos
  needs:
    - package:macos-11
  tags:
    - macos-11
  variables:
    PLATFORM_VER: "11"

test:macos-11:aarch64:
  extends: .test:macos
  needs:
    - package:macos-11:aarch64
  tags:
    - macos-11-aarch64
  variables:
    PLATFORM_VER: "11"

test:macos-12:
  extends: .test:macos
  needs:
    - package:macos-12
  tags:
    - macos-12
  variables:
    PLATFORM_VER: "12"

test:opensuse-15:x86_64:
  extends: .test:opensuse
  image: cincproject/omnibus-opensuse:15
  needs:
    - package:opensuse-15:x86_64
  tags:
    - docker-x86_64
  variables:
    PLATFORM_VER: "15"

test:opensuse-15:aarch64:
  extends: .test:opensuse
  image: cincproject/omnibus-opensuse:15
  needs:
    - package:opensuse-15:aarch64
  tags:
    - docker-aarch64
  variables:
    PLATFORM_VER: "15"

test:rhel-7:s390x:
  extends: .test:centos
  image: cincproject/omnibus-rhel:7
  needs:
    - package:rhel-7:s390x
  tags:
    - docker-s390x
  variables:
    PLATFORM_VER: "7"

test:rhel-8:s390x:
  extends: .test:centos
  image: cincproject/omnibus-rhel:8
  needs:
    - package:rhel-8:s390x
  tags:
    - docker-s390x
  variables:
    PLATFORM_VER: "8"

test:ubuntu-18.04:x86_64:
  extends: .test:ubuntu
  image: cincproject/omnibus-ubuntu:18.04
  needs:
    - package:ubuntu-18.04:x86_64
  tags:
    - docker-x86_64
  variables:
    PLATFORM_VER: "18.04"

test:ubuntu-18.04:aarch64:
  extends: .test:ubuntu
  image: cincproject/omnibus-ubuntu:18.04
  needs:
    - package:ubuntu-18.04:aarch64
  tags:
    - docker-aarch64
  variables:
    PLATFORM_VER: "18.04"

test:ubuntu-20.04:x86_64:
  extends: .test:ubuntu
  image: cincproject/omnibus-ubuntu:20.04
  needs:
    - package:ubuntu-20.04:x86_64
  tags:
    - docker-x86_64
  variables:
    PLATFORM_VER: "20.04"

test:ubuntu-20.04:aarch64:
  extends: .test:ubuntu
  image: cincproject/omnibus-ubuntu:20.04
  needs:
    - package:ubuntu-20.04:aarch64
  tags:
    - docker-aarch64
  variables:
    PLATFORM_VER: "20.04"

test:ubuntu-22.04:x86_64:
  extends: .test:ubuntu
  image: cincproject/omnibus-ubuntu:22.04
  needs:
    - package:ubuntu-22.04:x86_64
  tags:
    - docker-x86_64
  variables:
    PLATFORM_VER: "22.04"

test:ubuntu-22.04:aarch64:
  extends: .test:ubuntu
  image: cincproject/omnibus-ubuntu:22.04
  needs:
    - package:ubuntu-22.04:aarch64
  tags:
    - docker-aarch64
  variables:
    PLATFORM_VER: "22.04"

test:sources:
  image: cincproject/docker-auditor
  stage: test
  needs:
    - package:source
  tags:
    - docker-x86_64
  script:
    - apk add bash outils-sha256
    - cinc-auditor exec test/integration/cinc-sources --no-distinct-exit --reporter cli junit:junit.xml
  artifacts:
    reports:
      junit: junit.xml

test:windows-2012r2:
  extends: .test:windows
  needs:
    - package:windows-2012r2
  tags:
    - windows-x64-ucrt64
  variables:
    PLATFORM_VER: "2012r2"

# Deploy stage

.ssh-setup:
  before_script:
    - eval $(ssh-agent -s)
    - echo "${SSH_PRIVATE_KEY}" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "${SSH_KNOWN_HOSTS}" > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts

deploy:
  allow_failure: false
  stage: deploy
  extends: .ssh-setup
  # Only run if this is triggered from the web
  rules:
    - if: $CI_PIPELINE_SOURCE == "web"
      when: manual
    - when: never
  tags:
    - docker-x86_64
  dependencies:
    - package:source
    - package:amazonlinux-2:aarch64
    - package:amazonlinux-2:x86_64
    - package:centos-7:aarch64
    - package:centos-7:ppc64le
    - package:centos-7:x86_64
    - package:centos-8:aarch64
    - package:centos-8:ppc64le
    - package:centos-8:x86_64
    - package:centos-9:aarch64
    - package:centos-9:ppc64le
    - package:centos-9:x86_64
    - package:debian-9:x86_64
    - package:debian-10:aarch64
    - package:debian-10:x86_64
    - package:debian-11:aarch64
    - package:debian-11:x86_64
    - package:debian-12:aarch64
    - package:debian-12:x86_64
    - package:macos-10.15
    - package:macos-11
    - package:macos-11:aarch64
    - package:macos-12
    - package:opensuse-15:aarch64
    - package:opensuse-15:x86_64
    - package:rhel-7:s390x
    - package:rhel-8:s390x
    - package:ubuntu-18.04:aarch64
    - package:ubuntu-18.04:x86_64
    - package:ubuntu-20.04:aarch64
    - package:ubuntu-20.04:x86_64
    - package:ubuntu-22.04:aarch64
    - package:ubuntu-22.04:x86_64
    - package:windows-2012r2
  script:
    - ssh cinc@${DOWNLOADS_HOST} "mkdir -p /data/incoming/files/${CHANNEL}/cinc-foundation/$(cat VERSION)"
    - ssh cinc@${DOWNLOADS_HOST} "mkdir -p /data/incoming/source/${CHANNEL}/cinc-foundation/"
    - rsync -avH --delete data/ cinc@${DOWNLOADS_HOST}:/data/incoming/files/${CHANNEL}/cinc-foundation/$(cat VERSION)/
    - rsync -avH --delete source/ cinc@${DOWNLOADS_HOST}:/data/incoming/source/${CHANNEL}/cinc-foundation/
    - ssh cinc@${DOWNLOADS_HOST} "chmod 755 /data/incoming/files/${CHANNEL}/cinc-foundation/$(cat VERSION)/"

# Publish stage

publish:
  stage: publish
  extends: .ssh-setup
  dependencies: []
  # Only run if this is triggered from the web
  rules:
    - if: $CI_PIPELINE_SOURCE == "web"
      when: on_success
    - when: never
  tags:
    - downloads
  script:
    - sudo mkdir -p /data/mirror/{files,source}/${CHANNEL}/cinc-foundation
    - sudo /usr/bin/rsync -avH /data/incoming/files/${CHANNEL}/cinc-foundation/ /data/mirror/files/${CHANNEL}/cinc-foundation/
    - sudo /usr/bin/rsync -avH /data/incoming/source/${CHANNEL}/cinc-foundation/ /data/mirror/source/${CHANNEL}/cinc-foundation/
    - sudo -E -u cinc /usr/local/bin/update-cinc-api
    - ssh -q cinc@${MIRROR_HOST} "~/sync-from-master"

.cleanup:
  stage: cleanup
  dependencies: []
  variables:
    GIT_CHECKOUT: "false"
  when: always
  script:
    - sudo rm -rf chef-foundation/
    - sudo rm -rf ${CI_PROJECT_DIR}/cinc-project/distribution/foundation/

cleanup:macos-10.15:
  extends: .cleanup
  tags:
    - macos-10.15

cleanup:macos-11:
  extends: .cleanup
  tags:
    - macos-11

cleanup:macos-11-aarch64:
  extends: .cleanup
  tags:
    - macos-11-aarch64

cleanup:macos-12:
  extends: .cleanup
  tags:
    - macos-12
